// Auto Generated, do not edit.
import { Read } from "../../stream";
import * as PeriodUpdateStatData from "../structures/PeriodUpdateStatData";
import * as ReadNBytesInt64 from "../../common/ReadNBytesInt64";
import * as StatusEffectData from "../structures/StatusEffectData";
export type PKTInitPC = {
  unk0: number;
  unk1: bigint;
  unk2: number;
  unk3: number;
  unk4: number;
  unk5: bigint;
  playerId: bigint;
  unk6: number;
  unk7: number;
  unk8: string;
  unk9: boolean;
  unk10: number;
  statusEffectDatas: StatusEffectData.StatusEffectData[];
  unk11: Buffer;
  unk12: number;
  unk13: boolean;
  unk14: number;
  unk15: number;
  unk16: number;
  level: number;
  unk17: bigint;
  characterId: bigint;
  unk18: number;
  unk19: boolean;
  unk20: number;
  unk21: boolean;
  unk22: number;
  unk23: number;
  classId: number;
  unk24: bigint;
  unk25: number;
  unk26: number;
  unk27: number;
  unk28: number;
  unk29: number;
  unk30: number;
  unk31: number;
  unk32: number;
  struct_104: Buffer;
  unk33: number;
  unk34: Buffer;
  unk35: number;
  unk36: number;
  unk37: number;
  unk38?: number;
  unk39: number;
  unk40: bigint;
  struct_222: Buffer;
  statPair: { value: bigint; statType: number }[];
  struct_337: Buffer;
  unk41: number;
  unk42: number;
  periodUpdateStatDataList: PeriodUpdateStatData.PeriodUpdateStatData[];
  gearLevel: number;
  name: string;
  unk43: number;
  unk44: number;
};
export function read(buf: Buffer) {
  const reader = new Read(buf);
  const data = {} as PKTInitPC;
  data.unk0 = reader.u16();
  data.unk1 = reader.u64();
  data.unk2 = reader.u8();
  data.unk3 = reader.u16();
  data.unk4 = reader.u32();
  data.unk5 = reader.u64();
  data.playerId = reader.u64();
  data.unk6 = reader.u8();
  data.unk7 = reader.u8();
  data.unk8 = reader.string(7);
  data.unk9 = reader.bool();
  data.unk10 = reader.u8();
  data.statusEffectDatas = reader.array(reader.u16(), () => StatusEffectData.read(reader), 80);
  data.unk11 = reader.bytes(35);
  data.unk12 = reader.u32();
  data.unk13 = reader.bool();
  data.unk14 = reader.u8();
  data.unk15 = reader.u32();
  data.unk16 = reader.u8();
  data.level = reader.u16();
  data.unk17 = reader.u64();
  data.characterId = reader.u64();
  data.unk18 = reader.u8();
  data.unk19 = reader.bool();
  data.unk20 = reader.u32();
  data.unk21 = reader.bool();
  data.unk22 = reader.u16();
  data.unk23 = reader.u8();
  data.classId = reader.u16();
  data.unk24 = reader.u64();
  data.unk25 = reader.u8();
  data.unk26 = reader.u8();
  data.unk27 = reader.u32();
  data.unk28 = reader.u8();
  data.unk29 = reader.u8();
  data.unk30 = reader.u16();
  data.unk31 = reader.u8();
  data.unk32 = reader.f32();
  data.struct_104 = reader.bytes(reader.u16(), 63, 1);
  data.unk33 = reader.u32();
  data.unk34 = reader.bytes(25);
  data.unk35 = reader.u32();
  data.unk36 = reader.u8();
  data.unk37 = reader.u32();
  if (reader.bool()) data.unk38 = reader.u32();
  data.unk39 = reader.u8();
  data.unk40 = reader.u64();
  data.struct_222 = reader.bytes(reader.u16(), 3, 17);
  data.statPair = reader.array(
    reader.u16(),
    () => {
      const k = {} as { value: bigint; statType: number };
      k.value = ReadNBytesInt64.read(reader);
      k.statType = reader.u8();
      return k;
    },
    153
  );
  data.struct_337 = reader.bytes(reader.u16(), 104, 30);
  data.unk41 = reader.u8();
  data.unk42 = reader.u32();
  data.periodUpdateStatDataList = reader.array(reader.u16(), () => PeriodUpdateStatData.read(reader), 5);
  data.gearLevel = reader.f32();
  data.name = reader.string(20);
  data.unk43 = reader.u32();
  data.unk44 = reader.u8();
  return data;
}
export const name = "PKTInitPC";
export const opcode = 56597;
